import EditorialDescription from "@/components/EditorialDescription";
import { getOfferEditorial, editorialText } from "@/lib/offerEditorial";
import type { Metadata } from "next";
import { notFound, permanentRedirect } from "next/navigation";
import { extractOfferId, getOfferPath, type AllegroProduct } from "@/lib/allegro";
import OfferAddToCartButton from "@/components/OfferAddToCartButton";

export const dynamic = "force-dynamic";
type VideoLinks = { youtube?: string; tiktok?: string };
async function getProductBySlug(slug:string):Promise<AllegroProduct|null>{const id=extractOfferId(slug);if(!id)return null;try{const response=await fetch("https://trendeco.eu/api/allegro/offers",{cache:"no-store"});if(!response.ok)return null;const products=(await response.json()) as AllegroProduct[];return products.find(product=>product.id===id)??null;}catch{return null;}}
async function getVideos(offerId:string):Promise<VideoLinks>{try{const response=await fetch(`https://trendeco.eu/api/videos?offerId=${encodeURIComponent(offerId)}`,{next:{revalidate:300}});if(!response.ok)return{};return(await response.json()) as VideoLinks;}catch{return{};}}
function getDiscountedPrice(product:AllegroProduct){const price=Number.parseFloat(String(product.price).replace(",","."));if(!Number.isFinite(price))return product.price;const discounted=price*.95;const roundedDownToNine=Math.floor((discounted+1)/10)*10-1;return Math.max(9,roundedDownToNine).toFixed(2);}
function getYouTubeEmbedUrl(value?:string){if(!value)return null;try{const url=new URL(value);const id=url.hostname==="youtu.be"?url.pathname.split("/").filter(Boolean)[0]:url.searchParams.get("v")??url.pathname.match(/\/(?:shorts|embed)\/([^/?]+)/)?.[1];return id?`https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}`:null;}catch{return null;}}
function getTikTokEmbedUrl(value?:string){if(!value)return null;const id=value.match(/\/video\/(\d+)/)?.[1];return id?`https://www.tiktok.com/player/v1/${id}`:null;}
function PartyDetails({title,party}:{title:string;party:NonNullable<AllegroProduct["gpsr"]>["manufacturer"]}){if(!party)return null;const address=[party.address?.street,[party.address?.postalCode,party.address?.city].filter(Boolean).join(" "),party.address?.countryCode].filter(Boolean).join(", ");return <div><h3 className="font-black text-zinc-950">{title}</h3><p className="mt-1 font-semibold">{party.name}</p>{address&&<p className="mt-1">{address}</p>}<div className="mt-1 flex flex-wrap gap-x-4 gap-y-1">{party.contact?.email&&<a className="underline" href={`mailto:${party.contact.email}`}>{party.contact.email}</a>}{party.contact?.phoneNumber&&<a className="underline" href={`tel:${party.contact.phoneNumber}`}>{party.contact.phoneNumber}</a>}</div></div>}
function GpsrDetails({product}:{product:AllegroProduct}){const gpsr=product.gpsr;if(!gpsr)return null;return <section id="gpsr" className="mx-auto mt-8 max-w-5xl rounded-3xl bg-white p-6 shadow-sm md:p-10"><h2 className="text-2xl font-black">Informacje o produkcie i bezpieczeństwie (GPSR)</h2><div className="mt-6 grid gap-6 md:grid-cols-2"><PartyDetails title="Producent" party={gpsr.manufacturer}/><PartyDetails title="Podmiot odpowiedzialny w UE" party={gpsr.responsiblePerson}/></div></section>}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const product=await getProductBySlug(slug);if(!product)return{title:"Oferta niedostępna",robots:{index:false}};const canonical=getOfferPath(product);const discountedPrice=getDiscountedPrice(product);const copy=getOfferEditorial(product.id);const base=(copy?editorialText(copy):product.description)||product.name;const description=`${base.slice(0,110)} — sprawdź aktualną cenę, dostępność, dane techniczne i możliwość zakupu bezpośrednio w polskim sklepie TrendEco.`.slice(0,160);return{title:`${product.name} | TrendEco`,description,keywords:[product.name,product.category,"TrendEco","polski sklep","dane techniczne","cena","dostępność"],alternates:{canonical},openGraph:{title:product.name,description,url:`https://trendeco.eu${canonical}`,images:product.image?[{url:product.image,alt:product.name}]:[],type:"website"},twitter:{card:"summary_large_image",title:product.name,description,images:product.image?[product.image]:[]}};}
export default async function OfferPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const product=await getProductBySlug(slug);if(!product)notFound();const canonicalPath=getOfferPath(product);if(`/oferta/${slug}`!==canonicalPath)permanentRedirect(canonicalPath);const discountedPrice=getDiscountedPrice(product);const canonicalUrl=`https://trendeco.eu${canonicalPath}`;const videos=await getVideos(product.id);const youtubeEmbed=getYouTubeEmbedUrl(videos.youtube);const tiktokEmbed=getTikTokEmbedUrl(videos.tiktok);const editorial=getOfferEditorial(product.id);const structuredDescription=(editorial?editorialText(editorial):product.description)?.slice(0,5000)||`${product.name}. Produkt dostępny bezpośrednio w polskim sklepie TrendEco.`;
const productJsonLd={"@context":"https://schema.org","@type":"Product","@id":`${canonicalUrl}#product`,url:canonicalUrl,name:product.name,description:structuredDescription,image:product.image?[product.image]:undefined,sku:product.id,category:product.category,brand:{"@type":"Brand",name:product.gpsr?.manufacturer?.name||"TrendEco"},offers:{"@type":"Offer",url:canonicalUrl,priceCurrency:product.currency,price:discountedPrice,availability:product.stock>0?"https://schema.org/InStock":"https://schema.org/OutOfStock",itemCondition:"https://schema.org/NewCondition",seller:{"@type":"Organization","@id":"https://trendeco.eu/#organization",name:"TrendEco",url:"https://trendeco.eu"}}};
return <main className="min-h-screen bg-zinc-100 px-6 py-12 text-zinc-950"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(productJsonLd)}}/><article className="mx-auto grid max-w-5xl gap-10 rounded-3xl bg-white p-6 shadow-sm md:grid-cols-2 md:p-10"><div className="flex min-h-80 items-center justify-center rounded-2xl bg-zinc-50">{product.image?<img src={product.image} alt={product.name} className="max-h-[520px] max-w-full object-contain"/>:<span className="text-zinc-400">Brak zdjęcia</span>}</div><div><a href="/" className="text-sm font-semibold text-zinc-500">← Wróć do katalogu</a><p className="mt-8 text-sm font-bold uppercase tracking-wide text-orange-600">{product.category}</p><h1 className="mt-3 text-3xl font-black leading-tight">{product.name}</h1><p className="mt-6 text-3xl font-black text-green-700">Cena TrendEco: {discountedPrice} {product.currency}</p><p className="mt-2 font-black text-green-700">Darmowa dostawa na terenie Polski</p><p className="mt-3 text-zinc-600">Dostępność: {product.stock>0?`${product.stock} szt.`:"brak"}</p><OfferAddToCartButton product={{id:product.id,name:product.name,price:discountedPrice,currency:product.currency,image:product.image,stock:product.stock}}/><a href={product.url} target="_blank" rel="noopener noreferrer sponsored" className="mt-3 block rounded-full bg-orange-500 px-6 py-4 text-center text-lg font-black text-white">Zobacz ofertę na Allegro</a></div></article>{editorial?<EditorialDescription copy={editorial}/>:product.description&&<section className="mx-auto mt-8 max-w-5xl rounded-3xl bg-white p-6 shadow-sm md:p-10"><h2 className="text-2xl font-black">Opis i dane techniczne produktu</h2><p className="mt-6 whitespace-pre-line leading-7 text-zinc-700">{product.description}</p></section>}<GpsrDetails product={product}/>{(youtubeEmbed||tiktokEmbed)&&<section className="mx-auto mt-8 max-w-5xl rounded-3xl bg-white p-6 shadow-sm md:p-10"><h2 className="text-2xl font-black">Film produktu</h2>{youtubeEmbed&&<iframe src={youtubeEmbed} title={product.name} className="aspect-video w-full rounded-2xl"/>}{tiktokEmbed&&<iframe src={tiktokEmbed} title={product.name} className="min-h-[640px] w-full rounded-2xl"/>}</section>}</main>;
}